### PR TITLE
[Docker] Add Docker support

### PR DESCRIPTION
**Pull request by benjaminch**
This CL introduces docker support to this project.

Issue: #2

### CODE REVIEW

**Comment by benjaminch** [comment]
Hey @mtharrison,

What do you think about this one?

Thanks !

**Comment by benjaminch** [comment]
Hey @mtharrison ! Any chances you have time to look at this one ? :) 
Thanks !

**Comment by mtharrison** [comment]
Hi @benjaminch, thanks. Happy to accept this PR.

**Comment by benjaminch** [comment]
Thanks a lot @mtharrison :)

**Pull request merged**
